/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountDeletionTokens {
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface Activities {
  created_at: Generated<Timestamp>;
  id: string;
  object_iri: string | null;
  payload: unknown;
  type: string;
  user_id: string;
}

export interface BoardNotifications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  read_at: Timestamp | null;
  reason: "reply_to_post" | "reply_to_reply";
  reply_id: string;
  user_id: string;
}

export interface BoardPostLikes {
  created_at: Generated<Timestamp>;
  post_id: string;
  user_id: string;
}

export interface BoardPosts {
  activity_at: Generated<Timestamp>;
  body: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  edited_at: Timestamp | null;
  federated_note_iri: string | null;
  id: Generated<string>;
  kind: "site" | "template" | "question" | "chat";
  last_reply_at: Timestamp | null;
  last_reply_user_id: string | null;
  like_count: Generated<number>;
  reply_count: Generated<number>;
  solved_reply_id: string | null;
  title: string;
  user_id: string;
}

export interface BoardReplies {
  body: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  depth: number;
  edited_at: Timestamp | null;
  id: Generated<string>;
  like_count: Generated<number>;
  parent_id: string | null;
  path: ColumnType<string[], never, never>;
  post_id: string;
  user_id: string;
}

export interface BoardReplyLikes {
  created_at: Generated<Timestamp>;
  reply_id: string;
  user_id: string;
}

export interface BoardTemplateApplications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  user_id: string;
  version_id: string | null;
}

export interface BoardTemplateFiles {
  content_type: string;
  path: string;
  size_bytes: Int8;
  version_id: string;
}

export interface BoardTemplates {
  apply_count: Generated<number>;
  id: Generated<string>;
  latest_version_id: string | null;
  license: "cc-by-4.0" | "cc-by-sa-4.0" | "cc0-1.0";
  post_id: string;
  slug: string;
  user_id: string;
}

export interface BoardTemplateVersions {
  changelog: string | null;
  created_at: Generated<Timestamp>;
  data_collections: ColumnType<import("./board/template-collections").BoardTemplateCollection[], string | undefined, string>;
  file_count: number;
  id: Generated<string>;
  preview_rendered_at: Timestamp | null;
  size_bytes: Int8;
  source_path: string;
  template_id: string;
  version: number;
}

export interface CustomDomains {
  cloudflare_hostname_id: string;
  cloudflare_status: string;
  created_at: Generated<Timestamp>;
  hostname: string;
  id: Generated<string>;
  ownership_verification_name: string | null;
  ownership_verification_type: string | null;
  ownership_verification_value: string | null;
  ssl_status: string | null;
  ssl_validation_records: unknown | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  verification_errors: unknown | null;
  verified_at: Timestamp | null;
}

export interface EditDailyStats {
  date: Timestamp;
  edit_count: Generated<number>;
  user_id: string;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface Followers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  remote_actor_id: string;
  user_id: string;
}

export interface GithubDeployments {
  created_at: Generated<Timestamp>;
  delete_removed_files: boolean;
  deleted_paths: unknown;
  deploy_generation: Generated<number>;
  error_message: string | null;
  expires_at: Timestamp;
  finalized_at: Timestamp | null;
  github_ref: string;
  github_repository: string;
  github_repository_id: string | null;
  github_sha: string;
  id: string;
  manifest: unknown;
  status: Generated<string>;
  target_id: string;
  target_prefix: string;
  upload_prefix: string;
  uploaded_paths: Generated<unknown>;
  user_id: string;
}

export interface GithubDeployTargets {
  created_at: Generated<Timestamp>;
  delete_removed_files: Generated<boolean>;
  deploy_generation: Generated<number>;
  enabled: Generated<boolean>;
  github_ref: string;
  github_repository: string;
  github_repository_id: string | null;
  id: Generated<string>;
  last_deployed_at: Timestamp | null;
  last_github_sha: string | null;
  last_manifest: unknown | null;
  target_prefix: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface HomeDirectoryExports {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  download_expires_at: Timestamp | null;
  error_message: string | null;
  id: Generated<string>;
  r2_key: string | null;
  size_bytes: Int8 | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  user_id: string;
}

export interface HomeDirectorySizeHistory {
  id: Generated<string>;
  recorded_at: Generated<Timestamp>;
  size_bytes: number;
  user_id: string | null;
}

export interface LegacyIds {
  new_id: string;
  old_id: Int8;
  table_name: string;
}

export interface PageviewDailyStats {
  date: Timestamp;
  unique_visitors: Generated<number>;
  user_id: string;
  views: Generated<number>;
}

export interface Pageviews {
  id: Generated<string>;
  ip: string;
  path: Generated<string>;
  referrer: string | null;
  timestamp: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface PaymentEvents {
  created_at: Generated<Timestamp>;
  emailed_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  payment_id: string | null;
  subscription_id: string | null;
  summary: string;
  user_id: string | null;
}

export interface Payments {
  amount: number;
  attempt_key: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_reconciled_at: Timestamp | null;
  order_id: string;
  paid_at: Timestamp | null;
  period_end: Timestamp | null;
  period_start: Timestamp | null;
  raw: unknown | null;
  reconciliation_error: string | null;
  refund_keeps_plan: Generated<boolean>;
  refunded_amount: Generated<number>;
  refunded_at: Timestamp | null;
  status: string;
  subscription_id: string | null;
  toss_api_version: string | null;
  toss_approved_at: Timestamp | null;
  toss_currency: string | null;
  toss_flow: string | null;
  toss_method: string | null;
  toss_mid: string | null;
  toss_payment_key: string | null;
  toss_payment_type: string | null;
  toss_receipt_url: string | null;
  user_id: string;
}

export interface RemoteActors {
  created_at: Generated<Timestamp>;
  fetched_at: Generated<Timestamp>;
  id: Generated<string>;
  inbox_iri: string;
  iri: string;
  name: string | null;
  preferred_username: string | null;
  profile_url: string | null;
  shared_inbox_iri: string | null;
}

export interface RetiredBillingKeys {
  attempts: Generated<number>;
  billing_key: string;
  id: Generated<string>;
  last_attempted_at: Timestamp | null;
  last_error: string | null;
  retired_at: Generated<Timestamp>;
}

export interface Sessions {
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface SiteDataAccessTokens {
  client_id: string;
  collection_ids: string[];
  expires_at: Timestamp;
  hash: string;
  issued_at: Generated<Timestamp>;
  lifetime_seconds: Generated<number>;
  session_id: string;
}

export interface SiteDataAuthCodes {
  challenge: string;
  client_id: string;
  collection_ids: string[];
  expires_at: Timestamp;
  hash: string;
  session_id: string;
  token_lifetime_seconds: Generated<number>;
}

export interface SiteDataClients {
  collection_ids: string[];
  created_at: Generated<Timestamp>;
  id: string;
  redirect_uri: string;
  token_lifetime_seconds: Generated<number>;
  user_id: string;
}

export interface SiteDataCollections {
  id: Generated<string>;
  name: string;
  read_access: Generated<string>;
  user_id: string;
  write_access: Generated<string>;
}

export interface SiteDataDocuments {
  collection_id: string;
  created_at: Generated<Timestamp>;
  data: unknown;
  id: string;
  size_bytes: number;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface SiteDataFiles {
  content_type: string;
  created_at: Generated<Timestamp>;
  id: string;
  object_key: string;
  original_name: string;
  size_bytes: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface SiteDataRateLimits {
  count: number;
  key: string;
  user_id: string;
  window_start: Timestamp;
}

export interface Subscriptions {
  amount: number;
  billing_interval: string;
  canceled_at: Timestamp | null;
  card_registration_id: string | null;
  card_registration_kind: "signup" | "card_change" | null;
  charging_started_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  failed_charge_count: Generated<number>;
  id: Generated<string>;
  next_billing_at: Timestamp | null;
  payment_grace_notice_sent_at: Timestamp | null;
  plan: Generated<string>;
  plan_started_at: Generated<Timestamp>;
  renewal_notice_sent_at: Timestamp | null;
  status: string;
  toss_billing_key: string | null;
  toss_customer_key: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface SupporterFeatureUses {
  feature: string;
  first_used_at: Generated<Timestamp>;
  last_used_at: Generated<Timestamp>;
  user_id: string;
}

export interface TossWebhookDeliveries {
  duration_ms: number;
  event_type: string;
  headers: string | null;
  http_status: number;
  id: Generated<string>;
  outcome: string;
  payload: string | null;
  received_at: Generated<Timestamp>;
  retried_count: number | null;
  signature_check: string | null;
  subject: string | null;
  toss_status: string | null;
  transmission_id: string | null;
}

export interface UserKeys {
  created_at: Generated<Timestamp>;
  key_type: string;
  private_key: unknown;
  public_key: unknown;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  discoverable: Generated<boolean>;
  email: string | null;
  email_verified_at: Timestamp | null;
  home_directory_size_bytes: Generated<number | null>;
  home_directory_size_bytes_updated_at: Timestamp | null;
  id: Generated<string>;
  last_activity_sent_at: Timestamp | null;
  login_name: string;
  password_hash: string;
  site_rendered_at: Timestamp | null;
  site_title: string | null;
  site_updated_at: Timestamp | null;
  supporter_comp: Generated<boolean>;
  supporter_until: Timestamp | null;
  toss_customer_key: string | null;
}

export interface DB {
  account_deletion_tokens: AccountDeletionTokens;
  activities: Activities;
  board_notifications: BoardNotifications;
  board_post_likes: BoardPostLikes;
  board_posts: BoardPosts;
  board_replies: BoardReplies;
  board_reply_likes: BoardReplyLikes;
  board_template_applications: BoardTemplateApplications;
  board_template_files: BoardTemplateFiles;
  board_template_versions: BoardTemplateVersions;
  board_templates: BoardTemplates;
  custom_domains: CustomDomains;
  edit_daily_stats: EditDailyStats;
  email_verification_tokens: EmailVerificationTokens;
  followers: Followers;
  github_deploy_targets: GithubDeployTargets;
  github_deployments: GithubDeployments;
  home_directory_exports: HomeDirectoryExports;
  home_directory_size_history: HomeDirectorySizeHistory;
  legacy_ids: LegacyIds;
  pageview_daily_stats: PageviewDailyStats;
  pageviews: Pageviews;
  password_reset_tokens: PasswordResetTokens;
  payment_events: PaymentEvents;
  payments: Payments;
  remote_actors: RemoteActors;
  retired_billing_keys: RetiredBillingKeys;
  sessions: Sessions;
  site_data_access_tokens: SiteDataAccessTokens;
  site_data_auth_codes: SiteDataAuthCodes;
  site_data_clients: SiteDataClients;
  site_data_collections: SiteDataCollections;
  site_data_documents: SiteDataDocuments;
  site_data_files: SiteDataFiles;
  site_data_rate_limits: SiteDataRateLimits;
  subscriptions: Subscriptions;
  supporter_feature_uses: SupporterFeatureUses;
  toss_webhook_deliveries: TossWebhookDeliveries;
  user_keys: UserKeys;
  users: Users;
}
